### ISSUE TITLE
Move from global config to MPT based Config

### ISSUE THREAD

**Issue by ssardana96** [0chain/0chain#1029]
The following settings are to be kept in the MPT. They need a `update_global_settings` transaction to change.

The indicated settings [following global settings](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/minersc/globals.go#L26). These are either stored in the [global development object](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/config/dev_config.go#L5), in the chain or other ad-hock global variables.

We need to move the vales from their current location to the chain's [Config object](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/chain/config.go#L53).

```go
	State         // todo from development
	Dkg                               // todo from development
	ViewChange                        // todo from development
	BlockRewards                      // todo from development
	Storage                           // todo from development
	Faucet                            // todo from development
	Interest                          // todo from development
	Miner                             // todo from development
	Multisig                          // todo from development
	Vesting // todo from development
	Owner   // probably don't want this changeable
	BlockGenerationTimout        // todo from chain
	BlockGenerationRetryWaitTime // todo from chain
	RoundTimeoutsTimeoutCap // todo from chain
	TransactionTimeout // todo from global
	TransactionMinFee  // todo from global
	ClientDiscover // todo from chain
	StateSyncTimeout   // todo from chain
	StuckCheckInterval // todo from chain
	StuckTimeThreshold // todo from chain
	LfbTicketAhead                           // todo from chain

```

The following entries should not be held in the MPT but read from the `0chain.yaml` file
```  
dbs:
    events:
      enabled: true
      name: events_db
      user: zchain_user
      password: zchian
      host: postgres #localhost
      port: 5432
      max_idle_conns: 100
      max_open_conns: 200
      conn_max_lifetime: 20s
```

https://github.com/0chain/0chain/issues/736 also updates settings with new security levels.
