### ISSUE TITLE
Rate limits for providers - protect against DoDS.

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#1225]
To prevent against DDoS attacks we need to investigate rate limits for the event database, and providers.

**Comment by Sriep** [comment]
For event databse we have some [settings](https://github.com/0chain/0chain/blob/staging/docker.local/config/0chain.yaml#L130)
```yaml
  dbs:
    events:
      enabled: true
      name: events_db
      user: zchain_user
      password: zchian
      host: postgres #it will prefer to pick from env else it will be loaded from config
      port: 5432 #it will prefer to pick from env else it will be loaded from config
      max_idle_conns: 100
      max_open_conns: 200
      conn_max_lifetime: 20s
```
We can change these, do we need anything else to protect REST API endpoints?

**Comment by Sriep** [comment]
For providers' smartcontracts we have fees which should make DDos more difficult. Is this enough?

**Comment by peterlimg** [comment]
@Sriep smart contracts should be fine, we need to adjust the rate limit for none smart contracts APIs.

**Comment by guruhubb** [comment]
We also have rate limits for miners and sharders, which needs to be there for other providers (blobber, authorizer, validator)
```
  large_message_th_size: 5120 # anything greater than this size in bytes
  user_handlers:
    rate_limit: 100000000 # 100 per second
  n2n_handlers:
    rate_limit: 10000000000 # 10000 per second
```
