### ISSUE TITLE
Miner is not able to re-join network after a period down

### ISSUE THREAD

**Issue by fabioDMFerreira** [0chain/0chain#1499]
**Steps:**
- Launch 4 miners and 1 sharder
- Stop 1 miner
- Wait 3 minutes and stop another miner and restart miner stopped at step 2

**Expected** 
Network to keep creating rounds after the miner that was down for 3 minutes has returned to network.

**Actual**
Network is stuck in the same round before the moment that only 2 miners were active.

You can easily reproduce this scenario by running the next conductor test present in the file `conductor.no-view-change.fault-tolerance.yaml`:
```
  - name: "Miner goes down for 3 minutes simultaneously with coming up of the previous one"
    flow:
      - set_monitor: "sharder-1"
      - cleanup_bc: {}
      - wait_add:
          sharders: ["sharder-1"]
          miners: ["miner-1", "miner-2", "miner-3", "miner-4"]
          start: true
      - wait_round:
          shift: 20
          timeout: "1m"
      - stop: ["miner-4"]
      - wait_round:
          shift: 10
          timeout: "1m"
      - command:
          name: "sleep_3m"
      - stop: ["miner-3"]
      - start: ["miner-4"]
      - wait_round:
          shift: 10
          timeout: "1m"
    # COMMENTED NEXT LINES TO SIMPLIFY
    #   - command:
    #       name: "sleep_3m"
    #   - stop: ["miner-2"]
    #   - start: ["miner-3"]
    #   - wait_round:
    #       shift: 10
    #       timeout: "1m"
```
