### ISSUE TITLE
Add initial staking

### ISSUE THREAD

**Issue by dabasov** [0chain/0chain#1707]
Initial states should include initial stakes, that will lock ZCN to the stake pools directly bypassing balances in state record.

```yaml
initialStates:
  - id: 0330d8c6c37277b2b5dd112dd41f105703ee5723589d65079a7c13d8659125e0
    tokens: 1123123123
initialLocks:
  - id: 0330d8c6c37277b2b5dd112dd41f105703ee5723589d65079a7c13d8659125e0
    tokens: 11111111

```
