### ISSUE TITLE
0chain.yaml settings in mpt

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#496]
We want to be able to apply changes to `0chain.yaml` settings to a running chain. 

This means saving the settings the 0chain.yaml. 

We will need to develop a process where the chain reconfigures itself with any 0chain.yaml changes. This is probably best done at the start of each new round.

**Comment by Sriep** [comment]
Suggested list of settings to add to MPT

<details>
  <summary>alloc-cancel</summary>

```
development:
 state: true
 dkg: true
 view_change: false
 smart_contract:
  storage: true
  faucet: true
  zrc20: true
  interest: true
  miner: true
  multisig: true
  vesting: true

 block:
  min_block_size: 1
  max_block_size: 10
  max_byte_size: 1638400
  generators: 2
  replicators: 0
  generation:
   timeout: 15
   retry_wait_time: 5 #milliseconds
  proposal:
   max_wait_time: 180 # milliseconds
   wait_mode: static # static or dynamic
  consensus:
   threshold_by_count: 66 # percentage (registration)
   threshold_by_stake: 0 # percent
  sharding:
   min_active_sharders: 25 # percentage
   min_active_replicators: 25 # percentage
  validation:
   batch_size: 1000
  reuse_txns: false

 round_range: 10000000 - what is this for?
 round_timeouts:
  softto_min: 3000 #in miliseconds
  softto_mult: 3 #multiples of mean network time (mnt) softto = max{softo_min, softto_mult * mnt}
  round_restart_mult: 2 #number of soft timeouts before round is restarted
  timeout_cap: 0 # 0 indicates no cap
 transaction:
  payload:
   max_size: 98304 # bytes
  timeout: 30 # seconds
  min_fee: 0
 client:
  signature_scheme: bls0chain # ed25519 or bls0chain
  discover: true
 messages:
  verification_tickets_to: all_miners # generator or all_miners
 state:
  prune_below_count: 100 # rounds
  sync:
   timeout: 10 # seconds

 stuck:
  check_interval: 10 # seconds
  time_threshold: 60 #seconds

 smart_contract:
  timeout: 8000 # milliseconds

 lfb_ticket:
  rebroadcast_timeout: "15s" #
  ahead: 5          # should be >= 5
  fb_fetching_lifetime: "10s" #

 async_blocks_fetching:
  max_simultaneous_from_miners: 100
  max_simultaneous_from_sharders: 30

Also following items:
	read_lock_timeout: 1m
	write_lock_timeout: 1m
	max_lock_demand: 1.0
	min_offer_duration: 744h
	max_challenge_completion_time:10m
```

</details>

list of  55 settings.

1. 25 Settings are in the Chain.config object so are already set by solution:point_up:. :grinning:
2. 6 stored elsewhere in the chain but should be easy to merge with other settings.
3. 9 are kept as global objects, including the development settings. Work will need to be done to pass the settings to where they are needed.
4. 10 are unused or missing completely.
5. 2 seem to be in sc.yaml already or belong there.
6. 3 (at least) are used to set up worker threads. So these workers will need to be restarted if these settings change. Which needs careful thought.
