### ISSUE TITLE
yaml file, settings  changes

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#734]
We need changes to the following to sc.yaml
```yaml
  min_alloc_duration: "1 year"
  time_unit: "1 year"
  max_read_price: 0.0

    readpool:
      min_lock: 0.0 # tokens
      min_lock_period: 1 year
      max_lock_period: infinite
    writepool:
      min_lock: 0.1 # tokens
      min_lock_period: 1 year
      max_lock_period: infinite

     min_stake_duration: "3 years" 
```
`min_stake_duration` is a new field that puts a lower bound on stake duration.
We also need to support the `infinte` setting for `max_lock_period`.
