### ISSUE TITLE
Transaction to modify exempt transactions

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#906]
# Exempt from transaction fee

The following hardcoded list of transactions are exempt from transaction fee.
- add_miner
- miner_health_check
- add_sharder
- sharder_health_check
- contributeMpk
- sharder_keep
- shareSignsOrShares
- wait

# Change exempt transaction

We will be adding a new transaction that will modify the list of exempt transitions. We need the following changes.

1. Create an enumeration of smart contract endpoints.
2. Add to the genesis settings a list of smart contract transactions that are to be exempt from fees.
3. Add a REST API endpoint to get the list of transactions that are currently exempt from fees.
4. Add a new transaction that will either change a transaction to be exempt from fees or will change a transaction to be subject to fees.

# Genesis settings

We should add to the genesis yaml file the initial list of exempt transactions.
```yaml
transaction:
  payload:
    max_size: 98304 # bytes
  timeout: 30 # seconds
  min_fee: 0
  exempt:
  - add_miner
  - miner_health_check
  - add_sharder
  - sharder_health_check
  - contributeMpk
  - sharder_keep
  - shareSignsOrShares
  - wait
  - add_authoizer
  - blobber_health_check
```
